ccnr/ccnr_msg.c
NAME
ccnr/ccnr_msg.c -
Logging support for ccnr.
SYNOPSIS
Functions
int ccnr_msg_level_from_string (const char *s)
void ccnr_msg (struct ccnr_handle *h, const char *fmt,...)
Produce ccnr debug output.
void ccnr_debug_ccnb (struct ccnr_handle *h, int lineno, const char *msg, struct fdholder *fdholder, const unsigned char *ccnb, size_t ccnb_size)
Produce a ccnr debug trace entry.
Detailed Description
Logging support for ccnr.
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_msg.c.
Function Documentation
void ccnr_debug_ccnb (struct ccnr_handle * h, int lineno, const char * msg, struct fdholder * fdholder, const unsigned char * ccnb, size_t ccnb_size)
Produce a ccnr debug trace entry. Output is produced by calling ccnr_msg.
Parameters:
h the ccnr handle
lineno caller's source line number (usually __LINE__)
msg a short text tag to identify the entry
fdholder handle of associated fdholder; may be NULL
ccnb points to ccnb-encoded Interest or ContentObject
ccnb_size is in bytes
Definition at line 129 of file ccnr_msg.c.
Referenced by ccnr_answer_req(), load_policy(), r_match_consume_matching_interests(), r_proto_answer_req(), r_proto_begin_enumeration(), r_proto_bulk_import(), r_proto_continue_enumeration(), r_proto_dump_enums(), r_proto_expect_content(), r_proto_initiate_key_fetch(), r_proto_policy_complete(), r_proto_policy_update(), r_proto_start_write(), r_proto_start_write_checked(), r_store_lookup(), r_store_lookup_backwards(), r_store_next_child_at_level(), r_sync_enumerate(), r_sync_lookup(), and reap_enumerations().
void ccnr_msg (struct ccnr_handle * h, const char * fmt, ...)
Produce ccnr debug output. Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnr handle
fmt printf-like format string
Definition at line 86 of file ccnr_msg.c.
int ccnr_msg_level_from_string (const char * s)
Definition at line 48 of file ccnr_msg.c.
Referenced by main(), and r_init_debug_getenv().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.