.TH "ccnr/ccnr_msg.c" 3 "21 Aug 2012" "Version 0.6.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnr/ccnr_msg.c \- 
.PP
Logging support for ccnr.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBccnr_msg_level_from_string\fP (const char *s)"
.br
.ti -1c
.RI "void \fBccnr_msg\fP (struct \fBccnr_handle\fP *h, const char *fmt,...)"
.br
.RI "\fIProduce ccnr debug output. \fP"
.ti -1c
.RI "void \fBccnr_debug_ccnb\fP (struct \fBccnr_handle\fP *h, int lineno, const char *msg, struct \fBfdholder\fP *\fBfdholder\fP, const unsigned char *ccnb, size_t ccnb_size)"
.br
.RI "\fIProduce a ccnr debug trace entry. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Logging support for ccnr. 

Part of ccnr - CCNx Repository Daemon. 
.PP
Definition in file \fBccnr_msg.c\fP.
.SH "Function Documentation"
.PP 
.SS "void ccnr_debug_ccnb (struct \fBccnr_handle\fP * h, int lineno, const char * msg, struct \fBfdholder\fP * fdholder, const unsigned char * ccnb, size_t ccnb_size)"
.PP
Produce a ccnr debug trace entry. Output is produced by calling ccnr_msg. 
.PP
\fBParameters:\fP
.RS 4
\fIh\fP the ccnr handle 
.br
\fIlineno\fP caller's source line number (usually __LINE__) 
.br
\fImsg\fP a short text tag to identify the entry 
.br
\fIfdholder\fP handle of associated fdholder; may be NULL 
.br
\fIccnb\fP points to ccnb-encoded Interest or ContentObject 
.br
\fIccnb_size\fP is in bytes 
.RE
.PP

.PP
Definition at line 129 of file ccnr_msg.c.
.PP
Referenced by ccnr_answer_req(), load_policy(), r_match_consume_matching_interests(), r_proto_answer_req(), r_proto_begin_enumeration(), r_proto_bulk_import(), r_proto_continue_enumeration(), r_proto_dump_enums(), r_proto_expect_content(), r_proto_initiate_key_fetch(), r_proto_policy_complete(), r_proto_policy_update(), r_proto_start_write(), r_proto_start_write_checked(), r_store_lookup(), r_store_lookup_backwards(), r_store_next_child_at_level(), r_sync_enumerate(), r_sync_lookup(), and reap_enumerations().
.SS "void ccnr_msg (struct \fBccnr_handle\fP * h, const char * fmt,  ...)"
.PP
Produce ccnr debug output. Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines. 
.PP
\fBParameters:\fP
.RS 4
\fIh\fP the ccnr handle 
.br
\fIfmt\fP printf-like format string 
.RE
.PP

.PP
Definition at line 86 of file ccnr_msg.c.
.SS "int ccnr_msg_level_from_string (const char * s)"
.PP
Definition at line 48 of file ccnr_msg.c.
.PP
Referenced by main(), and r_init_debug_getenv().
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
