sync/SyncUtil.h
NAME
sync/SyncUtil.h -
Part of CCNx Sync.
SYNOPSIS
Data Structures
struct SyncNameAccumEntry
struct SyncNameAccum
struct SyncNodeAccum
Defines
#define SYNC_BAD_CMP (-2)
compare two names
Functions
void SyncNoteErr (const char *msg)
int SyncSetDecodeErr (struct ccn_buf_decoder *d, int val)
int SyncCheckDecodeErr (struct ccn_buf_decoder *d)
int64_t SyncCurrentTime (void)
int64_t SyncDeltaTime (int64_t mt1, int64_t mt2)
struct ccn_buf_decoder * SyncInitDecoderFromCharbufRange (struct ccn_buf_decoder *d, const struct ccn_charbuf *cb, ssize_t start, ssize_t stop)
struct ccn_buf_decoder * SyncInitDecoderFromCharbuf (struct ccn_buf_decoder *d, const struct ccn_charbuf *cb, ssize_t start)
int SyncDecodeHexDigit (char c)
int SyncDecodeUriChar (char c)
char * SyncHexStr (const unsigned char *cp, size_t sz)
int SyncNoteFailed (struct SyncRootStruct *root, char *where, char *why, int line)
void SyncNoteSimple (struct SyncRootStruct *root, char *where, char *s1)
void SyncNoteSimple2 (struct SyncRootStruct *root, char *where, char *s1, char *s2)
void SyncNoteSimple3 (struct SyncRootStruct *root, char *where, char *s1, char *s2, char *s3)
void SyncNoteUri (struct SyncRootStruct *root, char *where, char *why, struct ccn_charbuf *name)
void SyncNoteUriBase (struct SyncBaseStruct *base, char *where, char *why, struct ccn_charbuf *name)
int SyncCmpNamesInner (struct ccn_buf_decoder *xx, struct ccn_buf_decoder *yy)
compare two names advances both decoders, but early exit may leave them not fully over the names decoder error flags may be useful, though, if any errors occur
int SyncCmpNames (const struct ccn_charbuf *cbx, const struct ccn_charbuf *cby)
int SyncIsName (const struct ccn_charbuf *cb)
tests to see if charbuf refers to a name
int SyncComponentCount (const struct ccn_charbuf *name)
int SyncPatternMatch (const struct ccn_charbuf *pattern, const struct ccn_charbuf *name, int start)
simple pattern matching, where the pattern may contain components with a single 255 byte to match a single name component
int SyncPrefixMatch (const struct ccn_charbuf *prefix, const struct ccn_charbuf *name, int start)
int SyncComponentMatch (const struct ccn_charbuf *x, const struct ccn_charbuf *y)
int SyncGetComponentPtr (const struct ccn_charbuf *src, int comp, const unsigned char **xp, ssize_t *xs)
finds the bytes for a component (not including the tag) src must be a name, comp the component index
int SyncAppendAllComponents (struct ccn_charbuf *dst, const struct ccn_charbuf *src)
appends components from src to dst (both must be names)
struct ccn_charbuf * SyncNameForIndexbuf (const unsigned char *buf, struct ccn_indexbuf *comps)
Convenience routine to make a name from a ccn_indexbuf.
struct ccn_charbuf * SyncUriForName (struct ccn_charbuf *name)
Convenience routine to make a uri for a name.
void SyncGetHashPtr (const struct ccn_buf_decoder *hd, const unsigned char **xp, ssize_t *xs)
finds the hash code, storing the pointer to *xp and the length to *xs if the hash is valid (test for *xs != 0 to be sure) a hash code may be a ContentHash, or the last component of a Name (for convenience, a Component may also be used) non-destructive to the decoder no error codes, but a pointer is set only for valid cases
ssize_t SyncCmpHashesRaw (const unsigned char *xp, ssize_t xs, const unsigned char *yp, ssize_t ys)
void SyncAccumHashRaw (struct SyncLongHashStruct *hp, const unsigned char *xp, size_t xs)
void SyncAccumHashInner (struct SyncLongHashStruct *hp, const struct ccn_buf_decoder *d)
void SyncAccumHash (struct SyncLongHashStruct *hp, const struct ccn_charbuf *cb)
struct ccn_charbuf * SyncLongHashToBuf (const struct SyncLongHashStruct *hp)
uint32_t SyncSmallHash (const unsigned char *xp, ssize_t xs)
int SyncAppendTaggedNumber (struct ccn_charbuf *cb, enum ccn_dtag dtag, unsigned val)
int SyncAppendRandomBytes (struct ccn_charbuf *cb, int n)
int SyncAppendRandomHash (struct ccn_charbuf *cb, int n)
int SyncAppendRandomName (struct ccn_charbuf *cb, int nComp, int maxCompLen)
int SyncAppendElementInner (struct ccn_charbuf *cb, struct ccn_buf_decoder *d)
int SyncAppendElement (struct ccn_charbuf *dst, const struct ccn_charbuf *src)
struct ccn_charbuf * SyncExtractName (struct ccn_buf_decoder *d)
struct ccn_charbuf * SyncCopyName (const struct ccn_charbuf *name)
unsigned SyncParseUnsigned (struct ccn_buf_decoder *d, enum ccn_dtag dtag)
ssize_t SyncParseHash (struct ccn_buf_decoder *d)
ssize_t SyncParseName (struct ccn_buf_decoder *d)
struct SyncNameAccum * SyncAllocNameAccum (int lim)
struct SyncNameAccum * SyncFreeNameAccum (struct SyncNameAccum *na)
frees the name accum, but not the names
struct SyncNameAccum * SyncFreeNameAccumAndNames (struct SyncNameAccum *na)
frees the name accum and all of the names
int SyncNameAccumSorter (IndexSorter_Base base, IndexSorter_Index x, IndexSorter_Index y)
default sorter callback for a name accum uses CCN standard name order
int SyncNameAccumAppend (struct SyncNameAccum *na, struct ccn_charbuf *name, intmax_t data)
appends a new name with associated data important: the name is not copied!
struct ccn_charbuf * SyncNameAccumCanon (struct SyncNameAccum *na, const struct ccn_charbuf *name)
canonicalizes a name with respect to the given name accum should be used for relatively small canon sets
struct SyncNodeAccum * SyncAllocNodeAccum (int lim)
struct SyncNodeAccum * SyncFreeNodeAccum (struct SyncNodeAccum *na)
void SyncAccumNode (struct SyncNodeAccum *na, struct SyncNodeComposite *nc)
struct ccn_charbuf * SyncGenInterest (struct ccn_charbuf *name, int scope, int lifetime, int maxSuffix, int childPref, struct SyncNameAccum *excl)
given a spec for the desired fields (scope, lifetime, maxSuffix, child are omitted if negative)
struct ccn_charbuf * SyncNameForLocalNode (struct SyncRootStruct *root, struct ccn_charbuf *hash)
given a sync node hash,
int SyncPointerToContent (struct ccn_charbuf *cb, struct ccn_parsed_ContentObject *pco, const unsigned char **xp, size_t *xs)
given a charbuf cb for a content object, with optional parsing offsets in pco, sets *xp and *xs with the pointer and length of the actual content bytes
struct ccn_charbuf * SyncSignBuf (struct SyncBaseStruct *base, struct ccn_charbuf *cb, struct ccn_charbuf *name, long fresh, int flags)
given a charbuf cb and name for a content object, signs the bytes and
int SyncLocalRepoFetch (struct SyncBaseStruct *base, struct ccn_charbuf *name, struct ccn_charbuf *cb, struct ccn_parsed_ContentObject *pco)
given a local repo name and a buffer to fill, fills cb with the content object (note: not the content itself) pco is filled as a useful side effect, but may be NULL
int SyncLocalRepoStore (struct SyncBaseStruct *base, struct ccn_charbuf *name, struct ccn_charbuf *content, int flags)
given a sync node hash,
Detailed Description
Part of CCNx Sync.
Copyright (C) 2011 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file SyncUtil.h.
Define Documentation
#define SYNC_BAD_CMP (-2)
compare two names Returns:
>1 if cbx > cby, 0 if cby == cby, <-1 if cbx < cby
BAD_CMP for a parsing error
Definition at line 115 of file SyncUtil.h.
Referenced by SyncCmpNames(), SyncNameAccumSorter(), and SyncNodeCompareLeaf().
Function Documentation
void SyncAccumHash (struct SyncLongHashStruct * hp, const struct ccn_charbuf * cb)
Definition at line 621 of file SyncUtil.c.
Referenced by MakeNodeFromNames(), SyncNodeAddName(), and testReadBuilder().
void SyncAccumHashInner (struct SyncLongHashStruct * hp, const struct ccn_buf_decoder * d)
Definition at line 608 of file SyncUtil.c.
Referenced by SyncAccumHash(), and SyncNodeAddNode().
void SyncAccumHashRaw (struct SyncLongHashStruct * hp, const unsigned char * xp, size_t xs)
Definition at line 576 of file SyncUtil.c.
Referenced by SyncAccumHashInner().
void SyncAccumNode (struct SyncNodeAccum * na, struct SyncNodeComposite * nc)
Definition at line 953 of file SyncUtil.c.
Referenced by MakeNodeFromNames(), and newNodeCommon().
struct SyncNameAccum* SyncAllocNameAccum (int lim) [read]"Returns:
a new name accum with at least lim space for names
Definition at line 833 of file SyncUtil.c.
Referenced by addNameFromCompare(), copyFilter(), exclusionsFromHashList(), extractDeltas(), genTestRootRepos(), readAndAccumNames(), sortNames(), SyncAddRoot(), SyncNewBase(), SyncRootDecodeAndAdd(), SyncUpdateRoot(), and UpdateAction().
struct SyncNodeAccum* SyncAllocNodeAccum (int lim) [read]
Definition at line 935 of file SyncUtil.c.
Referenced by nodeFromNodes(), and UpdateAction().
int SyncAppendAllComponents (struct ccn_charbuf * dst, const struct ccn_charbuf * src)
appends components from src to dst (both must be names) Returns:
< 0 for an error
the number of components copied otherwise
Definition at line 468 of file SyncUtil.c.
Referenced by constructCommandPrefix(), and existingRootOp().
int SyncAppendElement (struct ccn_charbuf * dst, const struct ccn_charbuf * src)
Definition at line 757 of file SyncUtil.c.
Referenced by SyncEndComposite(), and SyncNodeAddName().
int SyncAppendElementInner (struct ccn_charbuf * cb, struct ccn_buf_decoder * d)
Definition at line 719 of file SyncUtil.c.
Referenced by extractBuf(), printTreeInner(), SyncAppendElement(), SyncExtractName(), and SyncTreeGenerateNames().
int SyncAppendRandomBytes (struct ccn_charbuf * cb, int n)
Definition at line 666 of file SyncUtil.c.
Referenced by SyncAppendRandomHash(), and SyncAppendRandomName().
int SyncAppendRandomHash (struct ccn_charbuf * cb, int n)
Definition at line 682 of file SyncUtil.c.
int SyncAppendRandomName (struct ccn_charbuf * cb, int nComp, int maxCompLen)
Definition at line 692 of file SyncUtil.c.
Referenced by testGenComposite().
int SyncAppendTaggedNumber (struct ccn_charbuf * cb, enum ccn_dtag dtag, unsigned val)
Definition at line 657 of file SyncUtil.c.
Referenced by NewDeltas(), sendSlice(), SyncEndComposite(), SyncResetComposite(), SyncRootAppendSlice(), and testRootBasic().
int SyncCheckDecodeErr (struct ccn_buf_decoder * d)
Definition at line 66 of file SyncUtil.c.
Referenced by appendComponents(), extractDeltas(), SyncAppendAllComponents(), SyncAppendElementInner(), SyncCmpNames(), SyncCmpNamesInner(), SyncComponentCount(), SyncComponentMatch(), SyncGetComponentPtr(), SyncGetHashPtr(), SyncIsName(), SyncParseComposite(), SyncParseUnsigned(), SyncPatternMatch(), SyncPrefixMatch(), and SyncRootDecodeAndAdd().
ssize_t SyncCmpHashesRaw (const unsigned char * xp, ssize_t xs, const unsigned char * yp, ssize_t ys)
Definition at line 564 of file SyncUtil.c.
Referenced by SyncHashEnter(), and SyncHashLookup().
int SyncCmpNames (const struct ccn_charbuf * cbx, const struct ccn_charbuf * cby)
Definition at line 227 of file SyncUtil.c.
Referenced by canonFilter(), doComparison(), sortNames(), SyncAddName(), SyncNameAccumCanon(), SyncNameAccumSorter(), SyncNodeCompareMinMax(), SyncNodeMaintainMinMax(), SyncTreeMergeNames(), and testReader().
int SyncCmpNamesInner (struct ccn_buf_decoder * xx, struct ccn_buf_decoder * yy)
compare two names advances both decoders, but early exit may leave them not fully over the names decoder error flags may be useful, though, if any errors occur
Definition at line 185 of file SyncUtil.c.
Referenced by SyncCmpNames(), and SyncNodeCompareLeaf().
int SyncComponentCount (const struct ccn_charbuf * name)"Returns:
number of components in the name
Definition at line 249 of file SyncUtil.c.
Referenced by ccns_send_root_advise_interest(), putFile(), putFileList(), SyncRegisterInterest(), SyncRegisterInterests(), SyncRootLookupName(), SyncSendRootAdviseInterest(), and SyncStartNodeFetch().
int SyncComponentMatch (const struct ccn_charbuf * x, const struct ccn_charbuf * y)"Returns:
number of components in the longest prefix of both x and y
-1 if there is a parsing error
Definition at line 407 of file SyncUtil.c.
Referenced by TryNodeSplit().
struct ccn_charbuf* SyncCopyName (const struct ccn_charbuf * name) [read]
Definition at line 781 of file SyncUtil.c.
Referenced by addNameFromCompare(), AddUpdateName(), fetchStablePoint(), storeHandler(), storeStablePoint(), SyncAddName(), and SyncInterestArrived().
int64_t SyncCurrentTime (void)
Definition at line 71 of file SyncUtil.c.
Referenced by ccns_root_advise_response(), ccns_send_root_advise_interest(), chooseRemoteHash(), CompareAction(), exclusionsFromHashList(), formatStats(), HeartbeatAction(), newActionData(), NewDeltas(), noteHash(), noteRemoteHash(), purgeOldEntries(), SendDeltasReply(), SyncAddRoot(), SyncHashEnter(), SyncNewBase(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncStartCompareAction(), SyncTreeMergeNames(), SyncUpdateRoot(), testReader(), and UpdateAction().
int SyncDecodeHexDigit (char c)
Definition at line 105 of file SyncUtil.c.
Referenced by parseAndAccumName().
int SyncDecodeUriChar (char c)
Definition at line 113 of file SyncUtil.c.
Referenced by parseAndAccumName().
int64_t SyncDeltaTime (int64_t mt1, int64_t mt2)
Definition at line 79 of file SyncUtil.c.
Referenced by ccns_root_advise_response(), chooseRemoteHash(), CompareAction(), exclusionsFromHashList(), formatStats(), HeartbeatAction(), purgeOldEntries(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncTreeMergeNames(), testReader(), and UpdateAction().
struct ccn_charbuf* SyncExtractName (struct ccn_buf_decoder * d) [read]
Definition at line 765 of file SyncUtil.c.
Referenced by extractDeltas(), SyncParseComposite(), and SyncRootDecodeAndAdd().
struct SyncNameAccum* SyncFreeNameAccum (struct SyncNameAccum * na) [read]
frees the name accum, but not the names Returns:
NULL
Definition at line 842 of file SyncUtil.c.
Referenced by exclusionsFromHashList(), genTestRootRepos(), testReadBuilder(), and testReader().
struct SyncNameAccum* SyncFreeNameAccumAndNames (struct SyncNameAccum * na) [read]
frees the name accum and all of the names Returns:
NULL
Definition at line 851 of file SyncUtil.c.
Referenced by ccns_send_root_advise_interest(), destroyCompareData(), extractDeltas(), FreeUpdateData(), putFileList(), SyncFreeBase(), SyncRemRoot(), SyncRootDecodeAndAdd(), SyncSendRootAdviseInterest(), SyncStartCompareAction(), and UpdateAction().
struct SyncNodeAccum* SyncFreeNodeAccum (struct SyncNodeAccum * na) [read]
Definition at line 944 of file SyncUtil.c.
Referenced by FreeUpdateData(), and nodeFromNodes().
struct ccn_charbuf* SyncGenInterest (struct ccn_charbuf * name, int scope, int lifetime, int maxSuffix, int childPref, struct SyncNameAccum * excl) [read]
given a spec for the desired fields (scope, lifetime, maxSuffix, child are omitted if negative) Returns:
the encoding for an interest
Definition at line 1022 of file SyncUtil.c.
Referenced by ccns_send_root_advise_interest(), existingRootOp(), fetchStablePoint(), getFile(), localStore(), putFile(), putFileList(), SyncHandleSlice(), SyncLocalRepoFetch(), SyncSendRootAdviseInterest(), SyncStartContentFetch(), SyncStartHeartbeat(), SyncStartNodeFetch(), and SyncStartSliceEnum().
int SyncGetComponentPtr (const struct ccn_charbuf * src, int comp, const unsigned char ** xp, ssize_t * xs)
finds the bytes for a component (not including the tag) src must be a name, comp the component index Returns:
< 0 for an error, 0 otherwise
Definition at line 444 of file SyncUtil.c.
Referenced by putFile(), putFileList(), and SyncHandleSlice().
void SyncGetHashPtr (const struct ccn_buf_decoder * hd, const unsigned char ** xp, ssize_t * xs)
finds the hash code, storing the pointer to *xp and the length to *xs if the hash is valid (test for *xs != 0 to be sure) a hash code may be a ContentHash, or the last component of a Name (for convenience, a Component may also be used) non-destructive to the decoder no error codes, but a pointer is set only for valid cases
Definition at line 531 of file SyncUtil.c.
Referenced by cacheEntryForElem(), SyncAccumHashInner(), and SyncTreeWorkerPush().
char* SyncHexStr (const unsigned char * cp, size_t sz)
Definition at line 125 of file SyncUtil.c.
Referenced by abortCompare(), ccns_root_advise_response(), findAndDeleteRoot(), formatStats(), MakeNodeFromNames(), newNodeCommon(), noteHash(), noteRemoteHash(), printTreeInner(), purgeOldEntries(), reportExclude(), setCovered(), SyncHandleSlice(), SyncInterestArrived(), SyncRegisterInterests(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncStartCompareAction(), SyncStartNodeFetch(), SyncUpdateRoot(), testReadBuilder(), and UpdateAction().
struct ccn_buf_decoder* SyncInitDecoderFromCharbuf (struct ccn_buf_decoder * d, const struct ccn_charbuf * cb, ssize_t start) [read]
Definition at line 98 of file SyncUtil.c.
Referenced by appendComponents(), appendExclusions(), SyncAccumHash(), SyncAppendAllComponents(), SyncAppendElement(), SyncCmpNames(), SyncComponentCount(), SyncComponentMatch(), SyncGetComponentPtr(), SyncIsName(), SyncNodeCompareLeaf(), SyncPatternMatch(), SyncPrefixMatch(), testEncodeDecode(), and testRootCoding().
struct ccn_buf_decoder* SyncInitDecoderFromCharbufRange (struct ccn_buf_decoder * d, const struct ccn_charbuf * cb, ssize_t start, ssize_t stop) [read]
Definition at line 84 of file SyncUtil.c.
Referenced by SyncInitDecoderFromCharbuf(), SyncInitDecoderFromElem(), SyncInitDecoderFromOffset(), and SyncNodeAddNode().
int SyncIsName (const struct ccn_charbuf * cb)
tests to see if charbuf refers to a name Returns:
1 for a name, 0 otherwise
Definition at line 240 of file SyncUtil.c.
int SyncLocalRepoFetch (struct SyncBaseStruct * base, struct ccn_charbuf * name, struct ccn_charbuf * cb, struct ccn_parsed_ContentObject * pco)
given a local repo name and a buffer to fill, fills cb with the content object (note: not the content itself) pco is filled as a useful side effect, but may be NULL Returns:
< 0 if the node fails
Definition at line 1163 of file SyncUtil.c.
Referenced by SyncCacheEntryFetch().
int SyncLocalRepoStore (struct SyncBaseStruct * base, struct ccn_charbuf * name, struct ccn_charbuf * content, int flags)
given a sync node hash, Returns:
the local repo name for the node
Definition at line 1141 of file SyncUtil.c.
Referenced by SyncCacheEntryStore().
struct ccn_charbuf* SyncLongHashToBuf (const struct SyncLongHashStruct * hp) [read]
Definition at line 628 of file SyncUtil.c.
Referenced by SyncEndComposite(), SyncParseComposite(), testReadBuilder(), and UpdateAction().
int SyncNameAccumAppend (struct SyncNameAccum * na, struct ccn_charbuf * name, intmax_t data)
appends a new name with associated data important: the name is not copied!
Definition at line 886 of file SyncUtil.c.
Referenced by addNameFromCompare(), AddUpdateName(), exclusionsFromHashList(), extractDeltas(), genTestRootRepos(), parseAndAccumName(), sortNames(), SyncAddName(), SyncNameAccumCanon(), SyncRootDecodeAndAdd(), and SyncTreeGenerateNames().
struct ccn_charbuf* SyncNameAccumCanon (struct SyncNameAccum * na, const struct ccn_charbuf * name) [read]
canonicalizes a name with respect to the given name accum should be used for relatively small canon sets Returns:
an equal name if it was in the accum
a copy of the name (and enters it) if no equal name was in the accum
Definition at line 911 of file SyncUtil.c.
Referenced by SyncAddRoot().
int SyncNameAccumSorter (IndexSorter_Base base, IndexSorter_Index x, IndexSorter_Index y)
default sorter callback for a name accum uses CCN standard name order
Definition at line 871 of file SyncUtil.c.
Referenced by sortNames(), SyncUpdateRoot(), and testReader().
struct ccn_charbuf* SyncNameForIndexbuf (const unsigned char * buf, struct ccn_indexbuf * comps) [read]
Convenience routine to make a name from a ccn_indexbuf. The storage for the returned charbuf is owned by the caller.
Returns:
a charbuf for the name (NULL if an error)
Definition at line 497 of file SyncUtil.c.
Referenced by ccns_root_advise_response(), and SyncRootAdviseResponse().
struct ccn_charbuf* SyncNameForLocalNode (struct SyncRootStruct * root, struct ccn_charbuf * hash) [read]
given a sync node hash, Returns:
the local repo name for the node
Definition at line 1057 of file SyncUtil.c.
Referenced by SyncCacheEntryFetch(), and SyncCacheEntryStore().
void SyncNoteErr (const char * msg)
Definition at line 47 of file SyncUtil.c.
Referenced by SyncAccumHashRaw(), SyncNameAccumAppend(), SyncNameAccumSorter(), SyncNameForIndexbuf(), SyncNoteFailed(), SyncSetCompErr(), and SyncSetDecodeErr().
int SyncNoteFailed (struct SyncRootStruct * root, char * where, char * why, int line)
Definition at line 141 of file SyncUtil.c.
Referenced by cacheEntryForElem(), ccns_root_advise_response(), comparisonFailed(), ensureRemoteEntry(), extractDeltas(), extractNode(), newNodeCommon(), nodeFromNodes(), sortNames(), SyncHandleSlice(), SyncRegisterInterest(), SyncRegisterInterests(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncStartCompareAction(), SyncStartContentFetch(), SyncStartNodeFetch(), and UpdateAction().
void SyncNoteSimple (struct SyncRootStruct * root, char * where, char * s1)
Definition at line 150 of file SyncUtil.c.
Referenced by abortCompare(), ccns_send_root_advise_interest(), CompareAction(), HeartbeatAction(), MakeNodeFromNames(), purgeOldEntries(), reportExclude(), setCovered(), SyncNotifyContent(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncTreeMergeNames(), TryNodeSplit(), and UpdateAction().
void SyncNoteSimple2 (struct SyncRootStruct * root, char * where, char * s1, char * s2)
Definition at line 155 of file SyncUtil.c.
Referenced by ccns_root_advise_response(), CompareAction(), MakeNodeFromNames(), newNodeCommon(), showCacheEntry1(), showCacheEntry2(), SyncHandleSlice(), SyncInterestArrived(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncStartNodeFetch(), TryNodeSplit(), and UpdateAction().
void SyncNoteSimple3 (struct SyncRootStruct * root, char * where, char * s1, char * s2, char * s3)
Definition at line 160 of file SyncUtil.c.
Referenced by SyncInterestArrived().
void SyncNoteUri (struct SyncRootStruct * root, char * where, char * why, struct ccn_charbuf * name)
Definition at line 165 of file SyncUtil.c.
Referenced by addNameFromCompare(), AddUpdateName(), ccns_root_advise_response(), ccns_send_root_advise_interest(), SendDeltasReply(), SyncAddName(), SyncCacheEntryFetch(), SyncInterestArrived(), SyncRegisterInterest(), SyncRegisterInterests(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncStartContentFetch(), SyncStartSliceEnum(), SyncTreeMergeNames(), and UpdateAction().
void SyncNoteUriBase (struct SyncBaseStruct * base, char * where, char * why, struct ccn_charbuf * name)
Definition at line 173 of file SyncUtil.c.
Referenced by SyncLocalRepoFetch(), and SyncLocalRepoStore().
ssize_t SyncParseHash (struct ccn_buf_decoder * d)
Definition at line 807 of file SyncUtil.c.
Referenced by SyncParseComposite().
ssize_t SyncParseName (struct ccn_buf_decoder * d)
Definition at line 814 of file SyncUtil.c.
Referenced by SyncParseComposite().
unsigned SyncParseUnsigned (struct ccn_buf_decoder * d, enum ccn_dtag dtag)
Definition at line 792 of file SyncUtil.c.
Referenced by extractDeltas(), SyncParseComposite(), SyncRootDecodeAndAdd(), and testRootBasic().
int SyncPatternMatch (const struct ccn_charbuf * pattern, const struct ccn_charbuf * name, int start)
simple pattern matching, where the pattern may contain components with a single 255 byte to match a single name component Returns:
number of matching components in the pattern if the name (starting at component index start) matches the prefix,
-1 if there is a parsing error or no match
Definition at line 271 of file SyncUtil.c.
Referenced by SyncRootLookupName().
int SyncPointerToContent (struct ccn_charbuf * cb, struct ccn_parsed_ContentObject * pco, const unsigned char ** xp, size_t * xs)
given a charbuf cb for a content object, with optional parsing offsets in pco, sets *xp and *xs with the pointer and length of the actual content bytes Returns:
< 0 for failure
Definition at line 1079 of file SyncUtil.c.
Referenced by existingRootOp(), fetchStablePoint(), and SyncHandleSlice().
int SyncPrefixMatch (const struct ccn_charbuf * prefix, const struct ccn_charbuf * name, int start)"Returns:
number of components in the prefix if the name (starting at component index start) matches the prefix,
-1 if there is a parsing error or no match
Definition at line 346 of file SyncUtil.c.
Referenced by SyncHandleSlice(), SyncNotifyContent(), and SyncRootLookupName().
int SyncSetDecodeErr (struct ccn_buf_decoder * d, int val)
Definition at line 59 of file SyncUtil.c.
Referenced by SyncExtractName(), and SyncGetHashPtr().
struct ccn_charbuf* SyncSignBuf (struct SyncBaseStruct * base, struct ccn_charbuf * cb, struct ccn_charbuf * name, long fresh, int flags) [read]
given a charbuf cb and name for a content object, signs the bytes and Returns:
the signed buffer (NULL for failure)
Definition at line 1096 of file SyncUtil.c.
Referenced by SendDeltasReply(), storeStablePoint(), SyncInterestArrived(), and SyncLocalRepoStore().
uint32_t SyncSmallHash (const unsigned char * xp, ssize_t xs)
Definition at line 638 of file SyncUtil.c.
Referenced by SyncHashEnter(), and SyncHashLookup().
struct ccn_charbuf* SyncUriForName (struct ccn_charbuf * name) [read]
Convenience routine to make a uri for a name. The storage for the returned charbuf is owned by the caller.
Returns:
the charbuf with the uri for the name (NULL if an error)
Definition at line 520 of file SyncUtil.c.
Referenced by existingRootOp(), putFile(), putFileList(), sendSlice(), SyncNoteUri(), SyncNoteUriBase(), SyncNotifyContent(), and SyncRegisterInterests().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.