sync/SyncBase.c
NAME
sync/SyncBase.c -
Part of CCNx Sync.
SYNOPSIS
Functions
void SyncSetErrInner (struct SyncBaseStruct *base, enum SyncErrCode code, char *file, int line)
void SyncClearErr (struct SyncBaseStruct *base)
struct SyncBaseStruct * SyncNewBase (struct ccnr_handle *ccnr, struct ccn *ccn, struct ccn_schedule *sched)
static int getEnvLimited (char *key, int lo, int hi, int def)
void SyncInit (struct SyncBaseStruct *bp)
void SyncFreeBase (struct SyncBaseStruct **bp)
int SyncNotifyContent (struct SyncBaseStruct *base, int enumeration, ccnr_accession item, struct ccn_charbuf *name)
void SyncShutdown (struct SyncBaseStruct *bp)
Detailed Description
Part of CCNx Sync.
Definition in file SyncBase.c.
Function Documentation
static int getEnvLimited (char * key, int lo, int hi, int def) [static]
Definition at line 95 of file SyncBase.c.
Referenced by SyncInit().
void SyncClearErr (struct SyncBaseStruct * base)
Definition at line 55 of file SyncBase.c.
Referenced by SyncFreeBase().
void SyncFreeBase (struct SyncBaseStruct ** bp)
Definition at line 228 of file SyncBase.c.
Referenced by ccns_close(), main(), and r_init_destroy().
void SyncInit (struct SyncBaseStruct * bp)
Definition at line 104 of file SyncBase.c.
Referenced by r_init_create().
struct SyncBaseStruct* SyncNewBase (struct ccnr_handle * ccnr, struct ccn * ccn, struct ccn_schedule * sched) [read]
Definition at line 69 of file SyncBase.c.
Referenced by ccns_open(), main(), and r_init_create().
int SyncNotifyContent (struct SyncBaseStruct * base, int enumeration, ccnr_accession item, struct ccn_charbuf * name)
Definition at line 256 of file SyncBase.c.
Referenced by r_sync_notify_content().
void SyncSetErrInner (struct SyncBaseStruct * base, enum SyncErrCode code, char * file, int line)
Definition at line 37 of file SyncBase.c.
void SyncShutdown (struct SyncBaseStruct * bp)
Definition at line 351 of file SyncBase.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.