.TH "SyncNameAccumEntry" 3 "21 Aug 2012" "Version 0.6.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncNameAccumEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBccn_charbuf\fP * \fBname\fP"
.br
.ti -1c
.RI "intmax_t \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 303 of file SyncUtil.h.
.SH "Field Documentation"
.PP 
.SS "intmax_t \fBSyncNameAccumEntry::data\fP"
.PP
Definition at line 305 of file SyncUtil.h.
.PP
Referenced by copyFilter(), sortNames(), SyncNameAccumAppend(), SyncNameAccumCanon(), SyncRegisterInterests(), and testReader().
.SS "struct \fBccn_charbuf\fP* \fBSyncNameAccumEntry::name\fP"
.PP
Definition at line 304 of file SyncUtil.h.
.PP
Referenced by appendExclusions(), canonFilter(), CompareAction(), copyFilter(), MakeNodeFromNames(), putFileList(), sortNames(), SyncAddName(), SyncFreeNameAccumAndNames(), SyncNameAccumAppend(), SyncNameAccumCanon(), SyncNameAccumSorter(), SyncRegisterInterests(), SyncRootAppendSlice(), SyncRootLookupName(), SyncTreeMergeNames(), testReadBuilder(), testReader(), TryNodeSplit(), and UpdateAction().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
