.TH "sync/SyncBase.c" 3 "21 Aug 2012" "Version 0.6.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sync/SyncBase.c \- 
.PP
Part of CCNx Sync.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSyncSetErrInner\fP (struct \fBSyncBaseStruct\fP *base, enum \fBSyncErrCode\fP code, char *file, int line)"
.br
.ti -1c
.RI "void \fBSyncClearErr\fP (struct \fBSyncBaseStruct\fP *base)"
.br
.ti -1c
.RI "struct \fBSyncBaseStruct\fP * \fBSyncNewBase\fP (struct \fBccnr_handle\fP *ccnr, struct ccn *ccn, struct ccn_schedule *sched)"
.br
.ti -1c
.RI "static int \fBgetEnvLimited\fP (char *key, int lo, int hi, int def)"
.br
.ti -1c
.RI "void \fBSyncInit\fP (struct \fBSyncBaseStruct\fP *bp)"
.br
.ti -1c
.RI "void \fBSyncFreeBase\fP (struct \fBSyncBaseStruct\fP **bp)"
.br
.ti -1c
.RI "int \fBSyncNotifyContent\fP (struct \fBSyncBaseStruct\fP *base, int enumeration, \fBccnr_accession\fP item, struct \fBccn_charbuf\fP *name)"
.br
.ti -1c
.RI "void \fBSyncShutdown\fP (struct \fBSyncBaseStruct\fP *bp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Part of CCNx Sync. 


.PP
Definition in file \fBSyncBase.c\fP.
.SH "Function Documentation"
.PP 
.SS "static int getEnvLimited (char * key, int lo, int hi, int def)\fC [static]\fP"
.PP
Definition at line 95 of file SyncBase.c.
.PP
Referenced by SyncInit().
.SS "void SyncClearErr (struct \fBSyncBaseStruct\fP * base)"
.PP
Definition at line 55 of file SyncBase.c.
.PP
Referenced by SyncFreeBase().
.SS "void SyncFreeBase (struct \fBSyncBaseStruct\fP ** bp)"
.PP
Definition at line 228 of file SyncBase.c.
.PP
Referenced by ccns_close(), main(), and r_init_destroy().
.SS "void SyncInit (struct \fBSyncBaseStruct\fP * bp)"
.PP
Definition at line 104 of file SyncBase.c.
.PP
Referenced by r_init_create().
.SS "struct \fBSyncBaseStruct\fP* SyncNewBase (struct \fBccnr_handle\fP * ccnr, struct ccn * ccn, struct ccn_schedule * sched)\fC [read]\fP"
.PP
Definition at line 69 of file SyncBase.c.
.PP
Referenced by ccns_open(), main(), and r_init_create().
.SS "int SyncNotifyContent (struct \fBSyncBaseStruct\fP * base, int enumeration, \fBccnr_accession\fP item, struct \fBccn_charbuf\fP * name)"
.PP
Definition at line 256 of file SyncBase.c.
.PP
Referenced by r_sync_notify_content().
.SS "void SyncSetErrInner (struct \fBSyncBaseStruct\fP * base, enum \fBSyncErrCode\fP code, char * file, int line)"
.PP
Definition at line 37 of file SyncBase.c.
.SS "void SyncShutdown (struct \fBSyncBaseStruct\fP * bp)"
.PP
Definition at line 351 of file SyncBase.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
