.TH "SyncNameAccumList" 3 "21 Aug 2012" "Version 0.6.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncNameAccumList \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBSyncNameAccumList\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBSyncNameAccum\fP * \fBaccum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file SyncPrivate.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBSyncNameAccum\fP* \fBSyncNameAccumList::accum\fP"
.PP
Definition at line 32 of file SyncPrivate.h.
.PP
Referenced by canonFilter().
.SS "struct \fBSyncNameAccumList\fP* \fBSyncNameAccumList::next\fP"
.PP
Definition at line 31 of file SyncPrivate.h.
.PP
Referenced by canonFilter().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
