sync/SyncBase.h
NAME
sync/SyncBase.h -
Part of CCNx Sync.
SYNOPSIS
Data Structures
struct SyncBaseStruct
struct SyncErrStruct
Enumerations
enum SyncErrCode { SyncErrCode_none = 0, SyncErrCode_bug = 1, SyncErrCode_caller = 2 }
Functions
void SyncSetErrInner (struct SyncBaseStruct *base, enum SyncErrCode code, char *file, int line)
void SyncClearErr (struct SyncBaseStruct *base)
struct SyncBaseStruct * SyncNewBase (struct ccnr_handle *ccnr, struct ccn *ccn, struct ccn_schedule *sched)
void SyncInit (struct SyncBaseStruct *bp)
void SyncFreeBase (struct SyncBaseStruct **bp)
int SyncNotifyContent (struct SyncBaseStruct *base, int enumeration, ccnr_accession item, struct ccn_charbuf *name)
void SyncShutdown (struct SyncBaseStruct *bp)
Detailed Description
Part of CCNx Sync.
Copyright (C) 2011 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file SyncBase.h.
Enumeration Type Documentation
enum SyncErrCode
Enumerator:
SyncErrCode_none
SyncErrCode_bug
SyncErrCode_caller
Definition at line 49 of file SyncBase.h.
Function Documentation
void SyncClearErr (struct SyncBaseStruct * base)
Definition at line 55 of file SyncBase.c.
Referenced by SyncFreeBase().
void SyncFreeBase (struct SyncBaseStruct ** bp)
Definition at line 228 of file SyncBase.c.
Referenced by ccns_close(), main(), and r_init_destroy().
void SyncInit (struct SyncBaseStruct * bp)
Definition at line 104 of file SyncBase.c.
Referenced by r_init_create().
struct SyncBaseStruct* SyncNewBase (struct ccnr_handle * ccnr, struct ccn * ccn, struct ccn_schedule * sched) [read]
Definition at line 69 of file SyncBase.c.
Referenced by ccns_open(), main(), and r_init_create().
int SyncNotifyContent (struct SyncBaseStruct * base, int enumeration, ccnr_accession item, struct ccn_charbuf * name)
Definition at line 256 of file SyncBase.c.
Referenced by r_sync_notify_content().
void SyncSetErrInner (struct SyncBaseStruct * base, enum SyncErrCode code, char * file, int line)
Definition at line 37 of file SyncBase.c.
void SyncShutdown (struct SyncBaseStruct * bp)
Definition at line 351 of file SyncBase.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.